### ISSUE TITLE
Internal server error when fetching a thumbnail of share

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1118]
## What I expect to happen
Show thumbnails of shares

## What really happened
Some shares do not have a thumbnail

## What I did that caused the issue - step by step
Open my list of shares and scroll.

## My environment
* Operating System and version: Win 10
* Web Browser and version: Firefox

## Thing I think the developers should know, images, links etc.
The server returns `500 - Internal Server Error` when opening [this image](https://israelhiking.osm.org.il/api/images/y9cM27rxjG?width=128&height=128) or [this image](https://israelhiking.osm.org.il/api/images/m7SX59eWb0?width=128&height=128). Both images were fetched while scrolling the shares list.

As far as I understand, this is the relevant entry in the site's error log:

```
2020-01-08 11:16:48.8809 |196 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HLSJP35OJD9J", Request id "0HLSJP35OJD9J:00000016": An unhandled exception was thrown by the application. System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at IsraelHiking.API.Services.ImageCreationService.GetTileImage(Point topLeft, Point offset, Int32 zoom, AddressAndOpacity addressTemplate) in C:\projects\site\IsraelHiking.API\Services\ImageCreationService.cs:line 384
   at IsraelHiking.API.Services.ImageCreationService.CreateSingleImageFromTiles(ImageCreationContext context) in C:\projects\site\IsraelHiking.API\Services\ImageCreationService.cs:line 231
   at IsraelHiking.API.Services.ImageCreationService.UpdateBackGroundImage(ImageCreationContext context) in C:\projects\site\IsraelHiking.API\Services\ImageCreationService.cs:line 205
   at IsraelHiking.API.Services.ImageCreationService.Create(DataContainer dataContainer, Int32 width, Int32 height) in C:\projects\site\IsraelHiking.API\Services\ImageCreationService.cs:line 85
   at IsraelHiking.API.Controllers.ImagesController.GetImageForShare(String id, Nullable`1 width, Nullable`1 height) in C:\projects\site\IsraelHiking.API\Controllers\ImagesController.cs:line 100
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by HarelM** [comment]
Seems like there's a problem with the response the server get for an image due to the background you chose for the share.
What do you think should be the error handling in this case? add a white tile instead of the failed tile?

**Comment by zstadler** [comment]
The backgrounds are freely available https sources and they can be seen even in incognito mode.

As a user, I expect these backgrounds to show in the thumbnail just like other extermal backgrounds: ESRI, Wikemadia, Jacotin, and others

**Comment by HarelM** [comment]
Not all of the images are available, although I'm not entirely sure this is the root cause here, but it is very likely this is it:
![image](https://user-images.githubusercontent.com/3269297/71989808-01a0dc00-323b-11ea-9d39-24d78d732b56.png)

**Comment by zstadler** [comment]
Missing tiles should be ignored, just like in the map view.

**Comment by HarelM** [comment]
Actually the problem is with the arggis server:
The following tile for example prints error 404 to the screen but returns a valid 200 response:
https://tiles.arcgis.com/tiles/tzxceqov0qqelztv/arcgis/rest/services/ortho2015a/mapserver/wmts/tile/1.0.0/ortho2015a/default/default028mm/11/827/1223
Our site that got a "valid" response tried to read the text as an image and fails.
I'll add a try catch around the image creation, but the cause of this bug is basically this specific tile server, other tiles servers, including ours return 404 when they can't find a tile...

**Comment by HarelM** [comment]
My bad. Problem was with a `ToLower` of the server address which caused the server to return this error page.
