### ISSUE TITLE
Unable to upload a recording - long URI in GPX

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1128]
## What I expect to happen
I should be able to upload a recording after the recording was completed.

## What really happened
I got an error message

## What I did that caused the issue - step by step
1. Create a private poi with an image
2. Save to file

## My environment
* Operating System and version: android
* Web Browser and version: n/a

**Comment by HarelM** [comment]
The exception stack trace on the server is as follows:
```
2020-01-17 13:50:07.5022 |251 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HLSQFECHH64M", Request id "0HLSQFECHH64M:00000014": An unhandled exception was thrown by the application. System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at IsraelHiking.API.Converters.GpxDataContainerConverter.<>c.<ToGpxWaypoint>b__9_0(LinkData l) in C:\projects\site\IsraelHiking.API\Converters\GpxDataContainerConverter.cs:line 168
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at IsraelHiking.API.Converters.GpxDataContainerConverter.ToGpxWaypoint(MarkerData marker) in C:\projects\site\IsraelHiking.API\Converters\GpxDataContainerConverter.cs:line 162
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at IsraelHiking.API.Converters.GpxDataContainerConverter.ToGpx(DataContainer container) in C:\projects\site\IsraelHiking.API\Converters\GpxDataContainerConverter.cs:line 28
   at IsraelHiking.API.Services.DataContainerConverterService.ToAnyFormat(DataContainer dataContainer, String format) in C:\projects\site\IsraelHiking.API\Services\DataContainerConverterService.cs:line 64
```
Seems like it fails to create a URI in the GPX file creation flow which results in an exception.

This should happen to all planning and recording with private pois with images I believe.

**Comment by HarelM** [comment]
Related to the following issues:
https://github.com/NetTopologySuite/NetTopologySuite.IO.GPX/issues/39
https://github.com/dotnet/runtime/issues/1857
