### ISSUE TITLE
Add problematic URLs to log file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1553]
## What I expect to happen
When [`normalizeTileURL`](https://github.com/maplibre/maplibre-gl-js/blob/89a5c3a232b6be5c5fac618cc3c6eac46fa3282f/src/util/mapbox.js#L104) fails, I'd like to see the problematic URL in the log file

## What really happened
The log file has this:

```
2021-07-18 11:00:09 | ERROR | Unable to parse URL object
Error: Unable to parse URL object
    at X (http://localhost/main.c212ceac30c46248ab84.js:1:166314)
    at W.normalizeTileURL (http://localhost/main.c212ceac30c46248ab84.js:1:164436)
    at n.loadTile (http://localhost/main.c212ceac30c46248ab84.js:1:567325)
    at n._loadTile (http://localhost/main.c212ceac30c46248ab84.js:1:607910)
    at n._addTile (http://localhost/main.c212ceac30c46248ab84.js:1:615743)
    at n._updateRetainedTiles (http://localhost/main.c212ceac30c46248ab84.js:1:614258)
    at n.update (http://localhost/main.c212ceac30c46248ab84.js:1:613205)
    at n.<anonymous> (http://localhost/main.c212ceac30c46248ab84.js:1:606490)
    at n.Tt.fire (http://localhost/main.c212ceac30c46248ab84.js:1:175575)
    at n.Tt.fire (http://localhost/main.c212ceac30c46248ab84.js:1:175893)
```

## What I did that caused the issue - step by step
Today, 2 users reported a problem with the app with this failure.

**Comment by HarelM** [comment]
I don't think I have a way to get the url from this error... Also I think the other issue about repaying the current layers is sufficient...

**Comment by zstadler** [comment]
Do you prooose that when this error occurs, the log file will include the URLs of all visible layers rather than the URL that caused the error?

**Comment by HarelM** [comment]
No, I'm proposing to ignore this error and simply write all the visible layer when reporting an issue.

**Comment by zstadler** [comment]
This is different than what I requested in #1552, but it is better and would address both scenarios!
