### ISSUE TITLE
Server error creating a thumbnail for a cloud save

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1648]
## What I expect to happen
Thimbnails would be shown in the "my saves on the cloud"

## What really happened
Some thumbnails are not showing.
![image](https://user-images.githubusercontent.com/1304610/139576271-ca7851d4-ad44-421e-ba4f-91ee98ec29ee.png)

## What I did that caused the issue - step by step
Open my saves on the cloud

## My environment
* Operating System and version:
* Web Browser and version:

## Things I think the developers should know, images, links etc.
To reproduce, open https://israelhiking.osm.org.il/api/images/1bkSNhNAVn

The site.log shows
```
2021-10-31 11:22:12.8117 | 47 |ERROR| Connection id "0HMCS3SRLPKAU", Request id "0HMCS3SRLPKAU:00000002": An unhandled exception was thrown by the application. Image cannot be loaded. Available decoders:ecoder
 - GIF : GifDecoder
 - JPEG : JpegDecoder
 - BMP : BmpDecoder
 - PNG : PngDecoder
```

The error.log show
```
2021-10-31 11:22:12.8117 | 47 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HMCS3SRLPKAU", Request id "0HMCS3SRLPKAU:00000002": An unhandled exception was thrown by the appli - TGA : TgaDecodermageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:context) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 243
 - GIF : GifDecoderAPI.Services.ImageCreationService.UpdateBackGroundImage(ImageCreationContext context) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 218
 - JPEG : JpegDecoderI.Services.ImageCreationService.Create(DataContainerPoco dataContainer, Int32 width, Int32 height) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 80
 - BMP : BmpDecoderAPI.Controllers.ImagesController.GetImageForShare(String id, Nullable`1 width, Nullable`1 height) in /net/IsraelHiking.API/Controllers/ImagesController.cs:line 107
 - PNG : PngDecoderNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)ontrollerActionInvoker invoker)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Byte[] data)FilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Ob   at IsraelHiking.API.Services.ImageCreationService.GetTileImage(Point topLeft, Point offset, Int32 zoom, AddressAndOpacity addressTemplate) in /net/IsraelHiking.API/Services/ImageCreationS   at IsraelHiking.API.Services.ImageCreationService.CreateSingleImageFromTiles(ImageCreationContext context) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 243
   at IsraelHiking.API.Services.ImageCreationService.UpdateBackGroundImage(ImageCreationContext context) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 218
   at IsraelHiking.API.Services.ImageCreationService.Create(DataContainerPoco dataContainer, Int32 width, Int32 height) in /net/IsraelHiking.API/Services/ImageCreationService.cs:line 80
   at IsraelHiking.API.Controllers.ImagesController.GetImageForShare(String id, Nullable`1 width, Nullable`1 height) in /net/IsraelHiking.API/Controllers/ImagesController.cs:line 107
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by HarelM** [comment]
Seems like the following tile is requested while creating the image:
https://israelhiking.osm.org.il/Hebrew/Tiles/11/1224/823.png
This tile doesn't return 404 status code and causes the above exception

**Comment by zstadler** [comment]
Resolved by https://github.com/IsraelHikingMap/Docker/commit/d6d28e0e795ada1f3b03c8170dd8082909152282
