### ISSUE TITLE
JS Error: `Cannot read properties of undefined (reading 'setLngLat')`

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/Site#1738]
## Bug?
JS Error appears in console. Might not be a bug

## What I expect to happen
No errors on console

## What really happened
Error in console...

## What I did that caused the issue - step by step
go to: https://israelhiking.osm.org.il/poi/Wikipedia/he_1545040

## My environment
- Chrome on Linux.
- I am logged in!
- Cannot reproduce in incognito mode.

## Things I think the developers should know, images, links etc.
```
main.606095c92cf08665.js:1 2022-07-13 15:31:10 | ERROR | Cannot read properties of undefined (reading 'setLngLat')
TypeError: Cannot read properties of undefined (reading 'setLngLat')
    at t.ngOnChanges (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:1147315)
    at t.ZC (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:30796)
    at r_ (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:35494)
    at Tg (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:35295)
    at Rc (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:34968)
    at OE (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:61357)
    at jle (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:61705)
    at OE (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:61730)
    at Yle (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:68466)
    at ble (https://israelhiking.osm.org.il/main.606095c92cf08665.js:1:62148)
```
![image](https://user-images.githubusercontent.com/66484/178734593-f61ee5f9-7655-4129-b001-a2f8e8759b5a.png)

**Comment by nonZero** [comment]
Can't reproduce after cleaning app data.

**Comment by HarelM** [comment]
I can't reproduce on my machine... (Win/chrome).
Also I don't see `setLatLng` call in the code in this repo, might be from ngx-maplibre-gl, maybe...
Can you share more steps to reproduce?
