### ISSUE TITLE
POI not found - כיפת עשת

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#798]
## What I expect to happen
Search to find "כיפת עשת"

## What really happened
This specific peak is not found.
The search result include another peak and POIs of other types. See the screenshot below.

## What I did that caused the issue - step by step
Search for "כיפת עשת"

## My environment
* Operating System and version: Win 10 home
* Web Browser and version: Firefox 56

## Thing I think the developers should know, images, links etc.
Search results:
![image](https://user-images.githubusercontent.com/1304610/45229632-095f1200-b2cf-11e8-8078-d213427e968e.png)

Direct link to [POI](https://israelhiking.osm.org.il/poi/OSM/node_5882330268?language=he)

**Comment by HarelM** [comment]
@zstadler Can you please amend the expected and step-by-step to be aligned with the image? I'm confused to which one of the is the correct one.

**Comment by HarelM** [comment]
Seems like the POI database wasn't rebuilt for the last month, which might cause this search issue, not sure though.
The error that can be seen in the log file is the following:
NetTopologySuite.Geometries.TopologyException: side location conflict [ (35.234320700000005, 31.777223900000003, NaN) ]
I can't figure out what's wrong with these geometries except the fact that there are two geometries at that point which might intersect.
I can add a `try-catch` around this code, but it feels like a work around...
Stack srace:
```
2018-09-07 05:11:27.8085 |220 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HLGJPT7VMJU7", Request id "0HLGJPT7VMJU7:0000009D": An unhandled exception was thrown by the application. NetTopologySuite.Geometries.TopologyException: side location conflict [ (35.234320700000005, 31.777223900000003, NaN) ]
   at NetTopologySuite.GeometriesGraph.EdgeEndStar.PropagateSideLabels(Int32 geomIndex)
   at NetTopologySuite.GeometriesGraph.EdgeEndStar.ComputeLabelling(GeometryGraph[] geomGraph)
   at NetTopologySuite.Operation.Relate.RelateComputer.LabelNodeEdges()
   at NetTopologySuite.Operation.Relate.RelateComputer.ComputeIM()
   at NetTopologySuite.Geometries.Geometry.Contains(IGeometry g)
   at IsraelHiking.API.Executors.OsmGeoJsonPreprocessorExecutor.<>c__DisplayClass9_0.<UpdatePlacesGeometry>b__0(Feature c)
```

**Comment by HarelM** [comment]
The reason for this was that someone added the old town of Jerusalem as a subarea and this created an invalid polygon.
Search after rebuild:
![image](https://user-images.githubusercontent.com/3269297/45258908-cafa4d80-b3c9-11e8-83e8-c2824b9b0da4.png)

**Comment by HarelM** [comment]
@zstadler good catch!
Published and can be found using the search.
